### ISSUE TITLE
pc文章无序列表变有序列表

### ISSUE THREAD

**Issue by zihanla** [liaocp666/halo-theme-daisy#10]
突然发现，明明写的是无序列表，后台编辑文章时也是无序，发布后显示的却是有序列表；
有点迷，用的NoSidebar模板

**Comment by liaocp666** [comment]
感谢反馈，确实有这个问题

**Comment by liaocp666** [comment]
已修复，更新一下吧 @zihanla 

![image](https://user-images.githubusercontent.com/27202776/191935832-491373f3-e7d6-4a0f-843b-dabb35723250.png)

**Comment by zihanla** [comment]
你好，刚刚更新了，自定义页面，还是没好，清除过缓存
[问题处](https://blog.hxcpl.cn/s/nav)
[![xA3NZD.png](https://s1.ax1x.com/2022/09/24/xA3NZD.png)](https://imgse.com/i/xA3NZD)

**Comment by liaocp666** [comment]
看起来没问题呀，无序列表就是小圆点

![图片](https://user-images.githubusercontent.com/27202776/192101097-bbb8a357-455f-4758-9015-5af68daa0290.png)

**Comment by zihanla** [comment]
阿哲，我的问题，我这边缓存没有清理干净，现在好了
