### ISSUE TITLE
一些文章页建议

### ISSUE THREAD

**Issue by Alex-Shen1121** [liaocp666/halo-theme-daisy#12]
个人认为在文章页，是否可以把侧栏的文章目录固定在画面里？现在用pc读长文章时，会容易跟丢。
另外个人非常喜欢风格的主题，希望保持更新，会继续关注的！

**Comment by liaocp666** [comment]
不好意思，没太懂你的意思，固定在画面里？哪个画面

**Comment by Yaklo** [comment]
> 不好意思，没太懂你的意思，固定在画面里？哪个画面

就是让文章目录随着页面滚动而不是固定，我也刚想提这个建议来着

**Comment by Alex-Shen1121** [comment]
> > 不好意思，没太懂你的意思，固定在画面里？哪个画面
> 
> 就是让文章目录随着页面滚动而不是固定，我也刚想提这个建议来着

对的 就是这个意思。例如我这篇博客https://www.codingshen.com/archives/go%E5%85%A5%E9%97%A8%E6%8C%87%E5%8D%97

希望下滑的时候，文章目录可以保持在右侧，比较适合长文章
![image](https://user-images.githubusercontent.com/73343630/197464738-530ca12d-ecd2-496b-9ba8-fe741d43e07c.png)

**Comment by liaocp666** [comment]
侧边栏其它的模块就完全被遮挡了呀

**Comment by Yaklo** [comment]
> 侧边栏其它的模块就完全被遮挡了呀

可以把文章目录放在最后一个，其他的放在前面，然后页面下划到文章目录时再跟着一起滚动。或者可选隐藏另外三个模块只留文章目录并跟着滚动

**Comment by jackloves111** [comment]
@liaocp666 我刚想提这个建议的，就发现已经有人提了，不知道博主有没有兴趣进行这样的改动，文章目录放在最后一个，其他的放在前面，然后页面下划到文章目录时再跟着一起滚动。或者可选隐藏另外三个模块只留文章目录并跟着滚动。

**Comment by liaocp666** [comment]
不是很想弄这个，有其他的小伙伴弄的话，欢迎 pr
