### ISSUE TITLE
能开放自定义样式吗

### ISSUE THREAD

**Issue by Yaklo** [liaocp666/halo-theme-daisy#14]
在主题设置页面里，改文件不好备份

**Comment by liaocp666** [comment]
自定义样式，这块内容可以在这里定义：`博客设置 - 其它设置 - 自定义全局 head`

**Comment by Yaklo** [comment]
> 自定义样式，这块内容可以在这里定义：`博客设置 - 其它设置 - 自定义全局 head`

这里也可以填css吗

**Comment by Yaklo** [comment]
<style type="text/css">

css内容

</style type="css">

虽然搞清楚了不过还是希望能加一个设置的地方2333333
