### ISSUE TITLE
API未找到

### ISSUE THREAD

**Issue by Dinosaurhou** [liaocp666/halo-theme-daisy#16]
已查阅Halo官方文档和官方论坛

Halo 开启 Api 服务，其填入的API是什么的API；

此主题的API指的是Halo中的API，但是Halo的API指的是什么？

**Comment by liaocp666** [comment]
@Dinosaurhou 参考以下步骤

1. 后台系统设置 - 博客设置
2. 点击右侧上边的“切换到高级选项”
3. API设置
4. 开启 API 服务，自定义填写 Access key 后保存
5. 复制 Access key 至主题设置保存

**Comment by Dinosaurhou** [comment]
已解决，谢谢博主。非常喜欢博主的主题，我会一直使用下去的！博主加油！
