### ISSUE TITLE
使用过后的一些小建议

### ISSUE THREAD

**Issue by zihanla** [liaocp666/halo-theme-daisy#3]
1. 与halo菜单的适配
2. 左侧边栏的信息显示，不加载内容
主题很好看，一直关注着加油！

**Comment by liaocp666** [comment]
没懂你意思诶

**Comment by zihanla** [comment]
啊这，我仔细看了文档，是我的问题，调整了下，还是有点小建议，希望有时间可以改善下。
目前是今天下载的此仓库主题。
1. 那个热门文章的加载，需要刷新才能显示，我观察了大大的，没有发现此情况
2. s/about页面，希望可以和大大一样不显示，右侧边栏
3. 外观设置，添加信息，最好能跟版权放在一个div盒子里面，放在最底下很突兀
4. 手机版访问logo的大小希望可以做限制，这样不用专门去改图片本身大小
叨扰大大了

**Comment by Cusox** [comment]
@zihanla
2. 可以在博客后台自定义页面修改页面模板为NoSidebar
3. 可以在macro.ftl中将备案信息放在版权的样式当中

**Comment by zihanla** [comment]
> @zihanla 2. 可以修改博客后台自定义页面的页面为侧边栏 3. 可以在macro.ftl中的微博后台上传的模板页面上没有



> @zihanla 2. 可以修改博客后台自定义页面的页面为侧边栏 3. 可以在macro.ftl中的微博后台上传的模板页面上没有
修改好了，谢谢哥，顺带看了下，老哥博客的logo，挺好看的
[涵有闲](https://blog.hxcpl.cn/)

**Comment by liaocp666** [comment]
> 1. 那个热门文章的加载，需要刷新才能显示，我观察了大大的，没有发现此情况

这点晚些时候帮你看看吧，这个可能是因为跳转是局部刷新导致的

> 3. 外观设置，添加信息，最好能跟版权放在一个div盒子里面，放在最底下很突兀

这就尴尬了，备案信息用小号浅色文字放到最底部，就是为了淡化这部门内容的显示。。。

> 4. 手机版访问logo的大小希望可以做限制，这样不用专门去改图片本身大小

算了，不限制了，每个人的logo不一样，有人可能是方形，圆形，异形……

@zihanla 

感谢 @lsilencej 回答

**Comment by liaocp666** [comment]
更新下最新主题看看 @zihanla

**Comment by zihanla** [comment]
> 更新下最新主题看看 @zihanla

好的，刚刚好在线

**Comment by zihanla** [comment]
> 这点晚些时候帮你看看吧，这个可能是因为跳转是局部刷新导致的

可以实时刷新了

> 这就尴尬了，备案信息用小号浅色文字放到最底部，就是为了淡化这部门内容的显示。。。

嗯，想法不一样，我想的是放一块舒服点，我单独改一下好了

> 算了，不限制了，每个人的logo不一样，有人可能是方形，圆形，异形……

嗯，有没有想法，手机布局直接隐藏掉logo,这样可能会更简洁，但是下拉菜单就尴尬了，哈哈，只是个人想法哈
我是pc用户，主题特别简洁，舒服，响应很快，加油！

**Comment by liaocp666** [comment]
手机布局隐藏的话，右边有图标，左边是空的，显的不对称，有点不好看。这部分再看吧。其它问题解决了，我关闭此 issue 了

**Comment by liaocp666** [comment]
移动端logo过大，已优化
