### ISSUE TITLE
如何直接打包生成静态文件部署

### ISSUE THREAD

**Issue by xdmdcp** [liaocp666/halo-theme-daisy#4]
你好，是这样的，我想知道如何调整才能弄成静态文件部署，类似 hexo 博客那种。

这个主题很好看，打算用这个界面做为个人网站入口，然后，通过这个页面跳转到博客网站，个人产品网站等。

感谢作者开源那么漂亮的主题。

**Comment by liaocp666** [comment]
如果要弄成 hexo 博客主题，需要重写此主题，因为毕竟这个是针对 halo 开发的主题，hexo 不通用的。

如果只是弄成单纯的静态网页，直接在浏览器里 ctrl + s 保存就可以了。然后按照你自己的需求改 HTML 代码就可以

@YuJian95

**Comment by xdmdcp** [comment]
好的，3q。
