### ISSUE TITLE
一眼就看中了这个主题，简洁美观。

### ISSUE THREAD

**Issue by ting1e** [liaocp666/halo-theme-daisy#5]
有几个小bug
+ 分页只写了归档页面的分页，其他页面的分页都有问题
+ 移动端用大头像基本上会占据整个屏幕，然后移动端没有搜索框
+ 显示友链的分组只是固定的home，希望可以添加能够自定义到设置里

然后我根据自己的喜好进行了一些修改  https://b.mortal.live/

另外我自己有一个问题就是，我想把文章页面的目录改成fixed的，这样在浏览文章的任意位置时，都可以快速跳转文章的各个章节，但这样的的话只能把页面的最新评论和最新文章这两栏去掉再把目录改成fixed，目前还没有想到好的解决方案

**Comment by liaocp666** [comment]
后面两点欢迎提个pr 😀
