### ISSUE TITLE
关于手机适配有个想法

### ISSUE THREAD

**Issue by zihanla** [liaocp666/halo-theme-daisy#9]
不知道，大大有没有考虑，手机版看文章时，不要热门评论、最新评论、友链，这样看起来应该会更简洁，当然这只是个人想法

**Comment by liaocp666** [comment]
确实可以，要不你来弄个？在主题设置里，做成可配置的开关

**Comment by zihanla** [comment]
止步于想法了，实践还是的靠大佬
